---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        delay: 5
        timeout: 600  
  tasks:  
    - name: "install python for Ansible."
    # Your code here
      apt:
        name: python
        state: present
  # Get the environment variables from CircleCI and add to the EC2 instance

 