---
- name: Install Python
  apt:
    name: python
    state: present

- name: Update/upgrade packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install nodejs, npm, and pm2
  apt:
    name:
      - nodejs
      - npm
    state: present
  become: yes
  become_user: root

- name: Install pm2
  npm:
    name: pm2
    global: yes